---
- hosts: all

  tasks:
    - name: install items via brew
      homebrew: name={{ item }} state=present update_homebrew=yes
      with_items:
        - ack
        - aspell
        - autojump
        - bash
        - bash-completion
        - chruby
        - curl
        - git
        - git-lfs
        - hub
        - mas
        - mongodb
        - mysql
        - nmap
        - node
        - oath-toolkit
        - openssl
        - phantomjs
        - postgresql
        - readline
        - redis
        - ruby-install
        - ssh-copy-id
        - sqlite
        - thefuck
        - tldr
        - tree
        - unar
        - wget
      tags: brew
